import 'package:flutter/cupertino.dart';

class terminos extends StatelessWidget {
  const terminos({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Text("Es responsabilidad de los usuarios el acceso voluntario al aplicativo móvil Consultorio Jurídico a la mano del aplicativo móvil, por lo cual, con sólo acceder a esta, los usuarios aceptan los términos y condiciones acá descritos.\n" +
        "Consultorio Jurídico a la mano deja constancia expresa que todos los datos, el contenido, la información y publicaciones, se encuentran amparadas por los lineamientos de la Legislación Colombiana, por tanto, cualquier diferencia que surja por el uso de este sitio web, y su contenido, será dirimida por la normatividad correspondiente de dicha legislación. Los productos y servicios anunciados no constituyen una oferta según los términos de la legislación colombiana, por lo que Consultorios Jurídicos a la mano, se reserva el derecho de modificar unilateralmente y sin previo aviso el contenido y los servicios prestados a través del presente sitio.\n" +
        "1.	USO DE LA APLICATIVO MÓVIL, CONTENIDOS Y SERVICIOS.\n" +
        "El ingreso al aplicativo móvil constituye consentimiento como usuario a utilizarla, junto con sus servicios y contenidos, sin contravenir la legislación vigente, la buena fe, los usos generalmente aceptados, el orden público, la moral y las buenas costumbres.\n" +
        "Asimismo, queda prohibido el uso del aplicativo móvil con fines ilícitos o lesivos, contra Consultorio Jurídico a la mano o contra cualquier tercero que, de cualquier forma, puedan resultar perjudicados directamente o por impedir el normal funcionamiento del aplicativo móvil.\n" +
        "Todos los bienes inmateriales susceptibles de ser protegidos tales como: marcas, nombres comerciales, lemas, enseñas, signos distintivos y demás contenidos en el aplicativo móvil, son de propiedad exclusiva de Consultorio Jurídico a la mano, por ende, es prohibida su reproducción total o parcial y por cualquier medio sin autorización previa y escrita de la misma.\n" +
        "TERCEROS DIFERENTES A CONSULTORIO JURIDICO A LA MANO\n" +
        "En el evento que Consultorio Jurídico a la mano posibilite el acceso a otros sitios de Internet a través de “Links” e “hipervínculos”, cuya inclusión en este sitio no compromete en ningún sentido a Consultorio Jurídico a la mano, así como tampoco significa el apoyo o patrocinio a tales productos, empresas, servicios o personas, e igualmente no se responsabiliza por el contenido y administración de ninguno de ellos.\n" +
        "Si el usuario adquiere algún producto o servicio a través de un tercero no autorizado por el aplicativo móvil, ésta no será responsable frente a ningún reclamo relativo a la solicitud en el aplicativo móvil a través de un tercero no autorizado, toda vez que no se emplearán intermediarios para los fines respectivos.\n" +
        "2.	INFORMACIÓN SUMINISTRADA\n" +
        "Al cargar información requerida o solicitada en el aplicativo móvil Consultorio Jurídico a la mano, o entregarlo por otros medios a la misma, el usuario que hubiese suministrado dicha información autoriza expresamente el tratamiento de dichos datos para los fines respectivos del aplicativo móvil, sin perjuicio de la protección que tendrán de conformidad con las actividades respectivas a ejecutar con éstos.\n" +
        "La política de privacidad de Consultorio Jurídico a la mano, en la que se establecen los métodos de tratamientos de datos e información personal que nuestros usuarios, comparten con nosotros, así como la recopilada a través de cualquier otro canal de comunicación, tanto de usuarios, como de sus funcionarios, también los derechos con los que cuentan los titulares de la información, así como la forma de ejercerlos.\n" +
        "Al momento de entregar cualquier tipo de información será necesario que previamente el usuario acepte nuestra autorización para el tratamiento de datos, de manera que no tenga ningún tipo de duda en cuanto a la forma en que se dará uso a sus datos personales.\n" +
        "3.	PARTICIPACIÓN DEL USUARIO\n" +
        "Las condiciones de conectividad serán responsabilidad de cada uno de los usuarios del aplicativo móvil, el acceso a este sitio estará sujeto a los controles de Consultorio Jurídico a la mano y aquellas propias del aplicativo móvil de internet, cuando se acceda a cualquiera de ellos, será responsabilidad del usuario tomar medidas de seguridad adecuadas y pertinentes para evitar virus u otro software malicioso.\n" +
        "Asimismo, para garantizar un adecuado uso del aplicativo móvil, el usuario deberá:\n" +
        "1.	Leer los términos y condiciones, políticas de privacidad y cualquier otra condición que se establezca en el aplicativo móvil Consultorio Jurídico a la mano.\n" +
        "2.	Emplear los contenidos, productos y servicios que ofrece Consultorio Jurídico a la mano para fines lícitos y ajustados a la ley colombiana o cualquier otro país. \n" +
        "3.	Ser responsable de cualquier actividad que se lleve a cabo bajo su registro.\n" +
        "4.	Utilizar el aplicativo móvil, únicamente de manera personal.\n" +
        "5.	Abstenerse de enviar correos electrónicos no deseados (SPAM) a otros usuarios, de llegar a obtener acceso a éstos, así como de introducir cualquier tipo de software o código de naturaleza destructiva.\n" +
        "6.	No incurrir en actuaciones ilícitas como daños o ataques informáticos, interceptación de comunicaciones, usurpación de identidad o falsedad de documentos.\n" +
        "7.	Canalizar las quejas, reclamos y denuncias a través de la sección de los canales de contacto establecidos tanto en la política de privacidad como en los presentes términos y condiciones.\n" +
        "4.	RESPONSABILIDAD DEL USUARIO\n" +
        "El uso del aplicativo móvil se realizará bajo responsabilidad de cada usuario, esta responsabilidad se extenderá al uso, por su parte o de cualquier tercero, de los usuarios y contraseñas de registro.\n" +
        "Sin perjuicio de lo anterior, Consultorio Jurídico a la mano se reserva el derecho a denegar en cualquier momento, y sin necesidad de previo aviso, el acceso al aplicativo móvil a aquellos usuarios que incumplan estas condiciones.\n" +
        "5.	FACULTADES Y DEBERES DE CONSULTORIOS JURIDICOS A LA MANO.\n" +
        "Por el hecho de que cualquier usuario acceda al aplicativo móvil, Consultorio Jurídico a la mano adquiere las siguientes facultades y deberes:\n" +
        "1.	Modificar unilateralmente, en cualquier tiempo y por cualquier razón, sin previo aviso, siempre que lo considere oportuno, la estructura y diseño del aplicativo móvil, así como los presentes Términos y Condiciones.\n" +
        "2.	Negar el registro a cualquier persona, en cualquier momento y por cualquier razón que considere pertinente.\n" +
        "3.	Incluir o no en el aplicativo móvil, el material recibido de los usuarios a su criterio, en el caso de incluirlo, podrá mantenerlo en el aplicativo móvil por el lapso que considere.\n" +
        "4.	Remover contenidos, que a juicio de Consultorio Jurídico a la mano sean ilegales, ofensivos, difamatorios o que de cualquier otra forma violen la ley o estos Términos y Condiciones. Así mismo, podrán ser retirados los contenidos que violen derechos intelectuales, ya sean de Consultorio Jurídico a la mano o de un tercero, a solicitud de éste.\n" +
        "5.	Utilizar la información personal y/o contenidos suministrados por los Usuarios de acuerdo con estos términos y condiciones, así como los fines previstos para el aplicativo móvil y los datos obtenidos.\n" +
        "7. EXCLUCIÓN DE RESPONSABILIDAD\n" +
        "Consultorio Jurídico a la mano no otorga ninguna garantía ni se hace responsable, en ningún caso, de los daños y perjuicios de cualquier naturaleza que pudieren traer derivados de los siguientes hechos:\n" +
        "1.	La falta de disponibilidad, mantenimiento y continuidad del funcionamiento del aplicativo móvil, cuando ello sea razonablemente posible Consultorio Jurídico a la mano advertirá previamente las interrupciones en el funcionamiento del aplicativo móvil.\n" +
        "2.	La falta de utilidad, adecuación o validez del aplicativo móvil y/o de sus servicios o contenidos para satisfacer necesidades, actividades o resultados concretos o expectativas del usuario.\n" +
        "3.	El uso ilícito, negligente, fraudulento o contrario a la ley o a los presentes términos y condiciones por parte del usuario.\n" +
        "4.	El incumplimiento por parte de terceros de sus obligaciones o compromisos en relación con los servicios prestados al usuario.\n" +
        "8	SEGURIDAD EN INTERNET\n" +
        "Consultorio Jurídico a la mano no controla ni garantiza, y por lo tanto no se hace responsable por la presencia de virus ni de otros elementos en los contenidos en el aplicativo móvil y que puedan aparecer a pesar del cumplimiento de sus deberes y debida diligencia, de manera que puedan producir alteraciones en el sistema informático (software y hardware) del Usuario o en los documentos electrónicos y ficheros almacenados en el sistema informático del Usuario.\n" +
        "Se entiende por código malicioso el nombre que se le da a cualquier programa que ingresa a un computador sin el conocimiento y la autorización explícita del responsable del mismo, dentro de los cuales se encuentran, los denominados VIRUS; TROYANOS; GUSANOS; PHISHING; PHARMING; ROOTKITS; BACKDOOR (PUERTAS TRASERAS), KEYLOGGERS (CAPTURADORES DE TECLADO), SCREEN LOGGERS, BOOTNETS, SNIFFERS (HUSMEADORES DE TRÁFICO DE LA RED), etc.\n" +
        "Teniendo en consideración la anterior definición, el usuario se obliga incondicional e irrevocablemente a garantizar que la información y documentación (incluidas imágenes, fotografías, animación, vídeo, audio, texto y otros elementos que forman parte del portal) que se entreguen a Consultorio Jurídico a la mano, se encuentran libres de Código Malicioso. Así mismo, se compromete a tomar las medidas necesarias para efectuar el control del Código Malicioso.\n" +
        "8.	FINALIDAD DE LA APLICATIVO MOVIL CONSULTORIOS JURIDICOS A LA MANO.\n" +
        "La aplicativo móvil Consultorio Jurídico a la mano, tendrá lugar como intermediario entre el usuario y el consultorio jurídico de la UNIVERSIDAD CATÓLICA LUIS AMIGÓ, a fin de que éste último, brinde las asesorías jurídicas a que habrá lugar según la determinación que se oriente a cada caso en particular, como consecuencia, los datos obtenidos mediante el registro de los usuarios, tendrá uso de conformidad con el procedimiento establecido en los presentes términos y condiciones, sin perjuicio de que éste pueda ser modificado de forma unilateral y en cualquier momento, de conformidad con las facultades que corresponden a la aplicativo móvil.\n" +
        "Como consecuencia de lo anterior, el proceso a ejecutar corresponderá al siguiente:\n" +
        "1.	El usuario se registrará en el aplicativo móvil, previa aceptación de los términos y condiciones, así como las políticas de privacidad que ésta determine.\n" +
        "2.	Una vez se registre la información que corresponda a: Nombre, Cédula, Teléfono, Correo, Caso particular, así como cualquier otro dato que se solicite en el formulario de registro, dicha información se conservará mediante un formulario que almacena dichas consultas en una base de datos de GOOGLE.\n" +
        "3.	Posteriormente se realizará la revisión respectiva en el consultorio jurídico de la UNIVERSIDAD CATÓLICA LUIS AMIGÓ, para determinar su viabilidad y generar la “ACEPTACIÓN” o “RECHAZO” de la misma.\n" +
        "4.	Dicha viabilidad se notificará al usuario y se dará continuidad o no al caso concreto.\n" +
        "5.	De ser viable, y aceptarse la solicitud del usuario, el caso se asignará a un estudiante activo del consultorio jurídico, razón por la cual, únicamente las directivas y docentes del consultorio, así como el estudiante al cual le fue asignado el caso concreto, dispondrán de la información suministrada por el usuario para la ejecución del respectivo proceso.\n" +
        "6.	Durante el trámite y una vez terminado el proceso que corresponda al consultorio jurídico, la información suministrada por el usuario se conservará en la base de datos de conformidad con estas políticas y condiciones y se procurará su salvaguarda de conformidad con el tratamiento de datos personales.\n" +
        "9.	 LEY APLICABLE Y JURÍSDICCIÓN\n" +
        "Estos términos y condiciones han sido dispuestos de conformidad con las leyes colombianas, si cualquier disposición en estos términos y condiciones pierde validez, por cualquier razón, todas las demás disposiciones conservarán su fuerza obligatoria, carácter vinculante y mantendrán todos sus efectos.\n" +
        "Cualquier acción o reclamación, el lugar de los presentes términos y condiciones es la ciudad de Manizales, Caldas, Colombia, y cualquier controversia que surja de su interpretación o aplicación, se someterá a los jueces de la República de Colombia.\n");
  }
}
